-- Drop existing policies if they exist
drop policy if exists "Allow public insert" on contact_submissions;
drop policy if exists "Allow service to read all" on contact_submissions;

-- Create the table if it doesn't exist
create table if not exists contact_submissions (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    name text not null,
    email text not null,
    phone text,
    service text,
    message text not null,
    status text default 'new'::text check (status in ('new', 'contacted', 'closed'))
);

-- Enable Row Level Security (RLS)
alter table contact_submissions enable row level security;

-- Create an insert policy that allows anyone to insert
create policy "Enable insert for anonymous users"
    on contact_submissions
    for insert
    to anon
    with check (true);

-- Create a select policy that allows anyone to read their own submissions
create policy "Enable read for anonymous users"
    on contact_submissions
    for select
    to anon
    using (true);

-- Grant necessary permissions to anon role
grant usage on sequence contact_submissions_id_seq to anon;
grant all on contact_submissions to anon; 